language: php
php:
  - 5.5
before_script:
  - ./bin/initialize-dependencies.sh
  - ./bin/initialize-ci.sh 2.0.7
  - php ./test/Integration/fixtures/load.php
script: bin/phpunit --group __nogroup__,integration
notifications:
  email:
    - stuart.carnie@gmail.com
