language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_script:
  - ./bin/initialize-dependencies.sh
  - sh -c ./bin/initialize-ci.sh 1.7.7
  - sh -c ./bin/initialize-ci.sh 1.6.2
  - php ./test/Integration/fixtures/load.php
script: phpunit --group __nogroup__,integration
notifications:
  email:
    - alessandro.nadalin@gmail.com
    - ing.davidino@gmail.com
    - suppakilla@gmail.com
    - weinmaster@gmail.com
